services:
  productdb:
    image: mysql:8.0.29
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile
  product.api:
    image: ${DOCKER_REGISTRY-}product.api:${PLATFORM:-linux}-${TAG-lastest}
    build:
      context: .
      dockerfile: Services/Product.API/Dockerfile
  # Volume section
volumes:
  sqlserver_data:
    name: sqlserver_data
  mysql_data:
    name: mysql_data